name: merge Artwork into Main

on:
  push:
    branches:
      - artwork

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge artwork -> master
        uses: devmasx/merge-branch@master
        with:
          type: force
          from_branch: 'artwork'
          target_branch: 'main'
          github_token: ${{ github.token }}